# Generated by Django 2.2 on 2020-03-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nxtgenUser', '0001_initial'),
        ('studentProfile', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nxtgenUser.NxtgenUser')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRegistrationNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherProfile.TeacherProfile')),
            ],
            options={
                'unique_together': {('institution', 'registration_number'), ('teacher', 'institution')},
            },
        ),
        migrations.CreateModel(
            name='TeacherFollowerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentProfile.StudentProfile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherProfile.TeacherProfile')),
            ],
            options={
                'unique_together': {('teacher', 'student')},
            },
        ),
    ]
