# Generated by Django 2.2 on 2020-03-20 17:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Class', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('repeat', models.BooleanField(default=False)),
                ('label', models.CharField(choices=[('emergency', 'Emergency'), ('event', 'Event'), ('holiday', 'Holiday'), ('exam', 'Exam'), ('industrial visite', 'Industrial visite'), ('fest', 'FEST')], max_length=50)),
                ('short_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DateAdditionalSubjectTeacherRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DateClassRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DateDepartmentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DateInstitutionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.InstitutionAnnouncementRelation')),
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='date.Date')),
            ],
        ),
        migrations.CreateModel(
            name='PublicDateInstitutionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('global', 'Global'), ('local', 'Local')], max_length=50)),
                ('date_institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='date.DateInstitutionRelation')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='DateSubjectTeacherRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.SubjectTeacherAnnouncementRelation')),
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='date.Date')),
                ('subject_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.ClassSubjectTeacherRelation')),
            ],
        ),
        migrations.CreateModel(
            name='DateSectionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.SectionAnnouncementRelation')),
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='date.Date')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.ClassSectionRelation')),
            ],
        ),
    ]
