# Generated by Django 2.2 on 2020-03-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('date', '0001_initial'),
        ('Class', '0002_auto_20200320_2307'),
        ('department', '0001_initial'),
        ('announcement', '0002_auto_20200320_2307'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateinstitutionrelation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='datedepartmentrelation',
            name='announcement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.DepartmentAnnouncementRelation'),
        ),
        migrations.AddField(
            model_name='datedepartmentrelation',
            name='date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='date.Date'),
        ),
        migrations.AddField(
            model_name='datedepartmentrelation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
        ),
        migrations.AddField(
            model_name='dateclassrelation',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.Class'),
        ),
        migrations.AddField(
            model_name='dateclassrelation',
            name='announcement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.ClassAnnouncementRelation'),
        ),
        migrations.AddField(
            model_name='dateclassrelation',
            name='date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='date.Date'),
        ),
        migrations.AddField(
            model_name='dateadditionalsubjectteacherrelation',
            name='additional_subject_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.AdditionalSubjectTeacherRelation'),
        ),
        migrations.AddField(
            model_name='dateadditionalsubjectteacherrelation',
            name='announcement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.AdditionalSubjectTeacherAnnouncementRelation'),
        ),
        migrations.AddField(
            model_name='dateadditionalsubjectteacherrelation',
            name='date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='date.Date'),
        ),
    ]
