# Generated by Django 2.2 on 2020-06-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nxtgenUser', '0001_initial'),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicQueryImproveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('form_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.TopicFormQuery')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nxtgenUser.NxtgenUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicExplanationImproveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('form_explanation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.ExplanationTopicFormQueryRelation')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nxtgenUser.NxtgenUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTopicQueryImproveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('form_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.SubTopicFormQuery')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nxtgenUser.NxtgenUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTopicExplanationImproveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('form_explanation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.ExplanationSubTopicFormQueryRelation')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nxtgenUser.NxtgenUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
