# Generated by Django 2.2 on 2020-03-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalSubjectTeacherAnnouncementRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archive', 'Archived')], default='draft', max_length=20)),
                ('block_comment', models.BooleanField(default=False)),
                ('archive_date', models.DateField(blank=True, null=True)),
                ('publish', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassAnnouncementRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CommentAnnouncementRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentAnnouncementRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTeacherAnnouncementRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='announcement.Announcement')),
                ('section_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.ClassSubjectTeacherRelation')),
            ],
        ),
        migrations.CreateModel(
            name='SectionAnnouncementRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='announcement.Announcement')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.ClassSectionRelation')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionAnnouncementRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='announcement.Announcement')),
            ],
        ),
    ]
