# Generated by Django 2.2 on 2020-03-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('commentExplanation', '0001_initial'),
        ('Class', '0002_auto_20200320_2307'),
        ('department', '0001_initial'),
        ('institution', '0001_initial'),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionannouncementrelation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='departmentannouncementrelation',
            name='announcement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='announcement.Announcement'),
        ),
        migrations.AddField(
            model_name='departmentannouncementrelation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
        ),
        migrations.AddField(
            model_name='commentannouncementrelation',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.Announcement'),
        ),
        migrations.AddField(
            model_name='commentannouncementrelation',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commentExplanation.Comment'),
        ),
        migrations.AddField(
            model_name='classannouncementrelation',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.Class'),
        ),
        migrations.AddField(
            model_name='classannouncementrelation',
            name='announcement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='announcement.Announcement'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AddField(
            model_name='additionalsubjectteacherannouncementrelation',
            name='announcement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='announcement.Announcement'),
        ),
        migrations.AddField(
            model_name='additionalsubjectteacherannouncementrelation',
            name='section_additional_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.AdditionalSubjectTeacherRelation'),
        ),
    ]
