# Generated by Django 2.2 on 2020-03-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('register_number', models.CharField(max_length=50)),
                ('invite_status', models.CharField(choices=[('send', 'SEND'), ('rejected', 'REJECTED'), ('excepted', 'EXCEPTED')], max_length=20)),
                ('profile_type', models.CharField(choices=[('stu', 'STUDENT'), ('teach', 'TEACHER')], max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
            options={
                'unique_together': {('institution', 'email'), ('institution', 'register_number')},
            },
        ),
    ]
