# Generated by Django 2.2 on 2020-06-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('date', '0002_auto_20200320_2307'),
        ('nxtgenUser', '0001_initial'),
        ('questionBank', '0001_initial'),
        ('form', '0002_subtopicexplanationimproverequest_subtopicqueryimproverequest_topicexplanationimproverequest_topicqu'),
        ('Class', '0003_auto_20200629_1041'),
        ('bookmarkShare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionshare',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionBank.Question'),
        ),
        migrations.AddField(
            model_name='questionshare',
            name='shared_on_additional_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Class.AdditionalSubjectTeacherRelation'),
        ),
        migrations.AddField(
            model_name='questionshare',
            name='shared_on_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Class.ClassSubjectTeacherRelation'),
        ),
        migrations.AddField(
            model_name='questionshare',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nxtgenUser.NxtgenUser'),
        ),
        migrations.AddField(
            model_name='questionbookmark',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionBank.Question'),
        ),
        migrations.AddField(
            model_name='questionbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nxtgenUser.NxtgenUser'),
        ),
        migrations.AddField(
            model_name='publicdatebookmark',
            name='public_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='date.PublicDateInstitutionRelation'),
        ),
        migrations.AddField(
            model_name='publicdatebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nxtgenUser.NxtgenUser'),
        ),
        migrations.AddField(
            model_name='formpostshare',
            name='form_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.FormPost'),
        ),
        migrations.AddField(
            model_name='formpostshare',
            name='shared_on_additional_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Class.AdditionalSubjectTeacherRelation'),
        ),
        migrations.AddField(
            model_name='formpostshare',
            name='shared_on_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Class.ClassSubjectTeacherRelation'),
        ),
        migrations.AddField(
            model_name='formpostshare',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nxtgenUser.NxtgenUser'),
        ),
        migrations.AddField(
            model_name='formpostbookmark',
            name='form_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.FormPost'),
        ),
        migrations.AddField(
            model_name='formpostbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nxtgenUser.NxtgenUser'),
        ),
        migrations.AlterUniqueTogether(
            name='questionshare',
            unique_together={('question', 'user', 'shared_on_additional_subject'), ('question', 'user', 'shared_on_subject')},
        ),
        migrations.AlterUniqueTogether(
            name='questionbookmark',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='publicdatebookmark',
            unique_together={('user', 'public_date')},
        ),
        migrations.AlterUniqueTogether(
            name='formpostshare',
            unique_together={('form_post', 'user', 'shared_on_subject'), ('form_post', 'user', 'shared_on_additional_subject')},
        ),
        migrations.AlterUniqueTogether(
            name='formpostbookmark',
            unique_together={('user', 'form_post')},
        ),
    ]
