# Generated by Django 2.2 on 2020-03-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacherProfile', '0001_initial'),
        ('studentProfile', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionteacherrelation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherProfile.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='institutionstudentrelation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='institutionstudentrelation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentProfile.StudentProfile'),
        ),
        migrations.AddField(
            model_name='institution',
            name='board_affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.BoardAffiliation'),
        ),
        migrations.AddField(
            model_name='institution',
            name='institute_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.InstituteType'),
        ),
        migrations.AlterUniqueTogether(
            name='institutionteacherrelation',
            unique_together={('teacher', 'institution')},
        ),
        migrations.AlterUniqueTogether(
            name='institutionstudentrelation',
            unique_together={('student', 'institution')},
        ),
    ]
