# Generated by Django 2.2 on 2020-03-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTeacherAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('attendance_for', models.CharField(choices=[('class', 'Class'), ('internal exam', 'Internal exam'), ('external exam', 'External exam')], max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.ClassSubjectTeacherRelation')),
            ],
            options={
                'unique_together': {('teacher', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AdditionalSubjectTeacherAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('attendance_for', models.CharField(choices=[('class', 'Class'), ('internal exam', 'Internal exam'), ('external exam', 'External exam')], max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.AdditionalSubjectTeacherRelation')),
            ],
            options={
                'unique_together': {('teacher', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SubjectAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.SubjectTeacherAttendance')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.ClassStudentRelation')),
            ],
            options={
                'unique_together': {('attendance', 'attendee')},
            },
        ),
        migrations.CreateModel(
            name='AdditionalSubjectAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.AdditionalSubjectTeacherAttendance')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.ClassStudentRelation')),
            ],
            options={
                'unique_together': {('attendance', 'attendee')},
            },
        ),
    ]
